name: Build with Emscripten

on:
  push:
    branches:
      - master  # Trigger on the master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the master branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest  # Run on Linux (Ubuntu)

    steps:
      # Initialize and update submodules
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'true'  # Initialize and update submodules

      # Set up Emscripten using emsdk
      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14  # Set up Emscripten SDK

      # Verify Emscripten installation
      - name: Verify Emscripten
        run: emcc -v  # Verify that emcc is working

      # Run the build script for WASM (or your other build steps)
      - name: Run build_wasm.sh (Linux)
        run: |
          chmod +x tools/scripts/linux/build_wasm.sh
          tools/scripts/linux/build_wasm.sh

      # Ensure /docs directory exists and copy gasyboy.wasm
      - name: Ensure /docs exists (Linux)
        run: mkdir -p docs

      - name: Copy gasyboy.wasm to /docs (Linux)
        run: cp build_wasm/gasyboy.wasm docs/

      # Commit and push gasyboy.wasm to the repo
      - name: Commit and push gasyboy.wasm
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/gasyboy.wasm
          git commit -m "Update gasyboy.wasm" || echo "No changes to commit"
          git push origin master  # Push to master branch
