name: Build and Deploy WASM

on:
  push:
    branches:
      - master  # Trigger on the master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the master branch
  release:
    types: [created]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build_wasm:
    runs-on: ubuntu-latest  # Run only on Linux (Ubuntu)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Set up Emscripten
      - name: Set up Emscripten
        uses: lovasoa/setup-emscripten@master
        with:
          emscripten-version: '1.38.47'  # Specify the version of Emscripten to use

      # Run the build script
      - name: Run build_wasm.sh (Linux)
        run: |
          chmod +x tools/scripts/linux/build_wasm.sh
          tools/scripts/linux/build_wasm.sh

      # Ensure /docs directory exists
      - name: Ensure /docs exists (Linux)
        run: mkdir -p docs

      # Copy gasyboy.wasm to /docs
      - name: Copy gasyboy.wasm to /docs (Linux)
        run: cp build_wasm/gasyboy.wasm docs/

      # Commit and push gasyboy.wasm to the repo
      - name: Commit and push gasyboy.wasm
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/gasyboy.wasm
          git commit -m "Update gasyboy.wasm" || echo "No changes to commit"
          git push origin master  # Push to master branch
